name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    container:
      image: fayehuang/ddjob:latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        pwd
